# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/gcp-cli
  gcp-cli: circleci/gcp-cli@1.8.4

  # https://circleci.com/orbs/registry/orb/circleci/gcp-gke
  gcp-gke: circleci/gcp-gke@1.1.0

  # https://circleci.com/orbs/registry/orb/circleci/kubernetes#commands-get-rollout-status
  k8s: circleci/kubernetes@0.11.1





executors:
  test-machine-executor:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-1604:202007-01

jobs:
  test1:
    executor: test-machine-executor
    steps:
      - run: gcloud version
      # - run: gcloud components update
      # - run:
      #     name: reinstall update
      #     command: |
      #       sudo rm -rf /opt/google-cloud-sdk
      #       cd ~/
      #       curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-308.0.0-linux-x86_64.tar.gz | tar xz
      #       echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV

      # - gcp-gke/install

      # - gcp-cli/install:
      #     version: 308.0.0
      # - k8s/install-kubectl

      # - run: gcloud version
      # - run: kubectl version

      # - run: gcloud components install kubectl
      # - run: kubectl version
      - run: docker run -ti  google/cloud-sdk:308.0.0 gcloud version
      - run: docker run -ti  google/cloud-sdk:308.0.0-slim gcloud version
      - run: docker run -ti  google/cloud-sdk:308.0.0-alpine gcloud version

      # - run: gcloud version

  image-test1:
    executor: gcp-cli/google
    steps:
      - run: gcloud version


  image-test2:
    docker:
      - image: google/cloud-sdk:308.0.0
    steps:
      - run: gcloud version

  image-test3:
    docker:
      - image: google/cloud-sdk:308.0.0-alpine
    steps:
      - run: gcloud version
      - k8s/install-kubectl
      - run: gcloud components install kubectl
      - run: gcloud version
      - run: kubectl version

  image-test4:
    docker:
      - image: circleci/node:10
    steps:
      - gcp-cli/install:
          version: 308.0.0
      - k8s/install-kubectl
      # - run: gcloud components install kubectl
      - run: gcloud version
      - run: kubectl version    



workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - test1
      # - image-test1
      # - image-test2
      # - image-test3
      # - image-test4


